routes/web.php
<?php

use App\Http\Controllers\PagesController;
use App\Http\Controllers\User\AccountController;
use App\Http\Controllers\User\ChatController;
use App\Http\Controllers\User\NotifikasiController;
use App\Http\Controllers\User\PengajuanController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PagesController::class, 'index'])->name('index');
Route::get('/layanan', [PagesController::class, 'showLayanan'])->name('layanan');
Route::get('/layanan/{url}', [PagesController::class, 'detailLayanan'])->name('layanan.detail');
Route::get('/tanya-jawab', [PagesController::class, 'showTanyaJawab'])->name('tanya-jawab');
Route::get('/kontak-kami', [PagesController::class, 'showKontakKami'])->name('kontak-kami');
Route::post('/send-message', [PagesController::class, 'sendMessage'])->name('send-message');

Route::group(['middleware' => 'auth', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
        Route::get('/', [PengajuanController::class, 'index'])->name('index');
        Route::get('/{url}/create', [PengajuanController::class, 'create'])->name('create');
        Route::post('/{url}/store', [PengajuanController::class, 'store'])->name('store');
        Route::get('/{no_pengajuan}/show', [PengajuanController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}/cancel', [PengajuanController::class, 'cancel'])->name('cancel');
        Route::get('/dokumen/{file}/download', [PengajuanController::class, 'downloadDokumen'])->name('download-dokumen');
    });
    Route::group(['prefix' => 'notifikasi', 'as' => 'notifikasi.'], function () {
        Route::get('/', [NotifikasiController::class, 'index'])->name('index');
        Route::get('/data', [NotifikasiController::class, 'data'])->name('data');
        Route::get('/count', [NotifikasiController::class, 'count'])->name('count');
        Route::get('/read/all', [NotifikasiController::class, 'readAll'])->name('read-all');
        Route::get('/{id}/read', [NotifikasiController::class, 'read'])->name('read');
    });
    Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
        Route::get('/', [AccountController::class, 'index'])->name('index');
        Route::post('/update', [AccountController::class, 'update'])->name('update');
        Route::get('/change-password', [AccountController::class, 'changePassword'])->name('change-password');
        Route::post('/update-password', [AccountController::class, 'updatePassword'])->name('update-password');
    });

    Route::group(['prefix' => 'chat', 'as' => 'chat.'], function () {
        Route::get('/{no_pengajuan}', [ChatController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}', [ChatController::class, 'send'])->name('send');
    });
});

Auth::routes();

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    <section id="hero">
        <div id="hero-area">
            <div class="overlay"></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12 col-lg-9 col-xs-12 text-center">
                        <div class="contents">
                            <h1 class="head-title ">
                                SMART DUKCAPIL KOTA CILEGON
                            </h1>
                            <p>
                                SALAH SATU INOVASI LAYANAN PENGGANTI TATAP MUKA, SEHINGGA PEMOHON ATAU WARGA DAPAT MENGURUS
                                DOKUMEN DARI MANAPUN DAN KAPANPUN
                            </p>
                            <a href="{{ route('layanan') }}" class="btn btn-common mt-3 px-3">LAYANAN KAMI</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="works section-padding">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 class="section-title">Cara Mengajukannya?</h3>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12">
                    <div class="works-item">
                        <div class="icon-box">
                            <i class="lni-users"></i>
                        </div>
                        <p><small>Buat Akun</small></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12">
                    <div class="works-item">
                        <div class="icon-box">
                            <i class="lni-bookmark-alt"></i>
                        </div>
                        <p><small>Buat Pengajuan Baru</small></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12">
                    <div class="works-item">
                        <div class="icon-box">
                            <i class="lni-timer"></i>
                        </div>
                        <p><small>Pengajuan Diproses</small></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12">
                    <div class="works-item">
                        <div class="icon-box">
                            <i class="lni-thumbs-up"></i>
                        </div>
                        <p><small>Selesai</small></p>
                    </div>
                </div>
                <hr class="works-line">
            </div>
        </div>
    </section>

    <section id="pricing-table" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="section-title">Jenis Layanan</h2>
                </div>
                @php
                    $count = 0;
                @endphp
                @forelse (get_layanan() as $layanan)
                    <?php if ($count == 3) {
                        break;
                    } ?>
                    <div class="col-lg-4 col-md-6 col-xs-12">
                        <div class="table">
                            <div class="icon">
                                <img src="{{ asset('') }}assets/img/category/img-3.png" alt="">
                            </div>
                            <div class="title">
                                <h3 class="text-muted">{{ $layanan->layanan }}</h3>
                            </div>
                            <ul class="description">
                                <li>{{ $layanan->keterangan }}</li>
                            </ul>
                            <a href="{{ route('layanan.detail', $layanan->url) }}" class="btn btn-common">Lihat Detail</a>
                        </div>
                    </div>
                    <?php $count++; ?>
                @empty
                    <strong class="text-center">Tidak ada layanan</strong>
                @endforelse
            </div>
            <div class="row mt-4">
                <div class="col-12">
                    <a href="{{ route('layanan') }}" class="btn btn-common">Semua Layanan Kami</a>
                </div>
            </div>
        </div>
    </section>

    <section class="counter-section section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 work-counter-widget">
                    <div class="counter">
                        <div class="icon"><i class="lni-users"></i></div>
                        <h2 class="counterUp">{{ get_counter()['warga'] }}</h2>
                        <p>Pengguna</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 work-counter-widget">
                    <div class="counter">
                        <div class="icon"><i class="lni-files"></i></div>
                        <h2 class="counterUp">{{ get_counter()['pengajuan'] }}</h2>
                        <p>Total Pengajuan</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 work-counter-widget">
                    <div class="counter">
                        <div class="icon"><i class="lni-timer"></i></div>
                        <h2 class="counterUp">{{ get_counter()['proses'] }}</h2>
                        <p>Dalam Proses</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 work-counter-widget">
                    <div class="counter">
                        <div class="icon"><i class="lni-thumbs-up"></i></div>
                        <h2 class="counterUp">{{ get_counter()['selesai'] }}</h2>
                        <p>Selesai</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/kontak-kami.blade.php
@extends('layouts.app')

@section('title', 'Kontak Kami')

@section('content')
    <div class="page-header" style="background: url({{ asset('') }}assets/img/banner1.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="product-title">Kontak Kami</h2>
                        <ol class="breadcrumb">
                            <li><a href="{{ route('index') }}">Home /</a></li>
                            <li class="current">Kontak Kami</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section id="google-map-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <object style="border:0; height: 450px; width: 100%;"
                        data="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d126960.71683987386!2d106.02329915192323!3d-6.0600500557508505!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e418f2db5ad3acb%3A0x2612b7844c39d804!2sDinas%20Kependudukan%20dan%20Catatan%20Sipil%20Kota%20Cilegon!5e0!3m2!1sen!2sid!4v1637738338252!5m2!1sen!2sid"></object>
                </div>
            </div>
        </div>
    </section>

    <section id="content" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-xs-12">
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    <form action="{{ route('send-message') }}" class="contact-form" method="POST">
                        @csrf
                        <h2 class="contact-title">
                            Kirim Pesan
                        </h2>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control @error('name') is-invalid @enderror"
                                                id="name" name="name" placeholder="Nama" required>
                                            @error('name')
                                                <div class="help-block with-errors text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <input type="email" name="email"
                                                class="form-control @error('email') is-invalid @enderror" id="email"
                                                placeholder="Email" required>
                                            @error('email')
                                                <div class="help-block with-errors text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control @error('subject') is-invalid @enderror"
                                                id="msg_subject" name="subject" placeholder="Subjek" required>
                                            @error('subject')
                                                <div class="help-block with-errors text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <textarea name="message"
                                                class="form-control @error('message') is-invalid @enderror"
                                                placeholder="Pesan Anda" rows="7" required></textarea>
                                            @error('message')
                                                <div class="help-block with-errors text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-common">Kirim Pesan</button>
                                <div id="msgSubmit" class="h3 text-center hidden"></div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4 col-md-4 col-xs-12">
                    <div class="information mb-4">
                        <h3>Alamat Kami</h3>
                        <div class="contact-datails">
                            <p>Jl. Kp. Jombang Kali No. 46, RT. 4 RW. 1, Kel. Ramanuju Kec. Purwakarta Kota Cilegon, Banten
                                42431.</p>
                        </div>
                    </div>
                    <div class="information">
                        <h3>Informasi Kontak</h3>
                        <div class="contact-datails">
                            <ul class="list-unstyled info">
                                <li><span>Email : </span>
                                    <p>dukcapilcilegon@gmail.com</p>
                                </li>
                                <li><span>Telepon : </span>
                                    <p>(0254) 380577</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/layanan-detail.blade.php
@extends('layouts.app')

@section('title', 'Detail Layanan')

@push('my-css')
    <style>
        .detail-layanan {
            padding: 0px 15px;
        }

        .detail-layanan ol li {
            list-style-type: decimal !important;
        }

    </style>
@endpush

@section('content')
    <div class="page-header" style="background: url({{ asset('') }}assets/img/banner1.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="product-title">Detail Layanan</h2>
                        <ol class="breadcrumb">
                            <li><a href="{{ route('index') }}">Home /</a></li>
                            <li class="current">Detail Layanan</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section id="content" class="section-padding">
        <div class="container">
            <div class="row">
                {{-- Card 1 --}}
                <div class="col-md-12 col-lg-12 col-xs-12">
                    <div class="services-item rounded" style="background-color: #6258C6;">
                        <div class="icon">
                            <i class="lni-bookmark-alt"></i>
                        </div>
                        <div class="services-content">
                            <h3><a href="#" class="text-white">{{ $layanan->layanan }}</a></h3>
                            <p class="text-white">{{ $layanan->keterangan }}</p>
                        </div>
                    </div>
                </div>
                {{-- Card 2 --}}
                <div class="col-md-12 col-lg-12 col-xs-12">
                    <div class="services-item rounded text-dark">
                        <div class="icon border">
                            <i class="lni-empty-file"></i>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="services-content">
                                    <h3 class="border-bottom mb-3">
                                        <a href="#">Informasi & Dokumen Layanan</a>
                                    </h3>
                                    <div class="row">
                                        <div class="col-md-12 text-dark mb-3">
                                            <strong>Persyaratan</strong>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value="" id="persyaratan"
                                                    {{ $layanan->layananPersyaratan->count() > 0 ? 'checked' : '' }}
                                                    onclick="return false;">
                                                <label class="form-check-label" for="persyaratan">
                                                    Pemohon harus mengupload dokumen persyaratan sebelum pengajuan dapat
                                                    diproses lebih
                                                    lanjut.
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-12 text-dark mb-3">
                                            <strong>Pengambilan Dokumen Kependudukan</strong>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value=""
                                                    id="pengambilan_sendiri"
                                                    {{ $layanan->pengambilan_sendiri ? 'checked' : '' }}
                                                    onclick="return false;">
                                                <label class="form-check-label" for="pengambilan_sendiri">
                                                    Pemohon dapat mengambil dokumen kependudukan sendiri
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value="" id="cetak_dokumen"
                                                    {{ $layanan->cetak_dokumen ? 'checked' : '' }}
                                                    onclick="return false;">
                                                <label class="form-check-label" for="cetak_dokumen">
                                                    Pemohon dapat mencetak dokumen kependudukan sendiri
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value=""
                                                    id="pengiriman_ekspedisi"
                                                    {{ $layanan->pengiriman_ekspedisi ? 'checked' : '' }}
                                                    onclick="return false;">
                                                <label class="form-check-label" for="pengiriman_ekspedisi">
                                                    Dokumen Kependudukan dapat dikirimkan kepada pemohon via ekspedisi
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-12 text-dark mb-3">
                                            <strong>Dokumen Pendukung</strong>
                                            <div class="detail-layanan">
                                                @if ($layanan->layananDokumen)
                                                    <ol>
                                                        @foreach ($layanan->layananDokumen as $dokumen)
                                                            @if ($dokumen->aktif)
                                                                <li>{{ $dokumen->dokumen }}&nbsp;|&nbsp;<a
                                                                        href="{{ route('user.pengajuan.download-dokumen', $dokumen->file) }}">Download</a>
                                                                </li>
                                                            @endif
                                                        @endforeach
                                                    </ol>
                                                @else
                                                    <ul>
                                                        <li><span class="text-warning">Tidak ada dokumen pendukung.</span>
                                                        </li>
                                                    </ul>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="services-content">
                                    <h3 class="border-bottom mb-3">
                                        <a href="#">Mekanisme Pengajuan</a>
                                    </h3>
                                    <p>Mekanisme pengajuan yang harus dilakukan oleh pemohon terkait layanan ini:</p>
                                    <div class="detail-layanan">
                                        <ol>
                                            <li>Pemohon menyiapkan persyaratan yang dibutuhkan</li>
                                            <li>Pemohon melakukan pengajuan Layanan</li>
                                            <li>Pemohon mengisi form pengajuan dengan data isian yang diperlukan</li>
                                            <li>Pemohon mengupload dokumen yang dibutuhkan</li>
                                            <li>Operator memproses pengajuan dari pemohon</li>
                                            <li>Operator menerbitkan dokumen kependudukan</li>
                                            <li>Pemohon mengambil sendiri dokumen kependudukan ke Kantor Dinas</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Card 3 --}}
                <div class="col-md-12 col-lg-12 col-xs-12">
                    <div class="services-item rounded text-dark">
                        <div class="icon">
                            <i class="lni-bookmark-alt"></i>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="services-content">
                                    <h3 class="border-bottom mb-3">
                                        <a href="#">Persyaratan</a>
                                    </h3>
                                    <p>Daftar persyaratan yang harus diupload oleh pemohon sebelum melakukan pengajuan
                                        layanan:</p>
                                    <div class="detail-layanan">
                                        @if ($layanan->layananPersyaratan)
                                            <ol>
                                                @foreach ($layanan->layananPersyaratan as $persyaratan)
                                                    @if ($persyaratan->aktif)
                                                        <li>{{ $persyaratan->persyaratan }}</li>
                                                    @endif
                                                @endforeach
                                            </ol>
                                        @else
                                            <ul>
                                                <li><span class="text-warning">Tanpa persyaratan.</span>
                                                </li>
                                            </ul>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="services-content">
                                    <h3 class="border-bottom mb-3">
                                        <a href="#">Isian Pengajuan</a>
                                    </h3>
                                    <p>Daftar isian pada form pengajuan yang harus diisi oleh pemohon:</p>
                                    <div class="detail-layanan">
                                        @if ($layanan->layananIsian)
                                            {!! $layanan->layananIsian->isian !!}
                                        @else
                                            <ul>
                                                <li><span class="text-warning">Tanpa Form Isian.</span>
                                                </li>
                                            </ul>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Card 4 --}}
                <div class="col-md-12 col-lg-12 col-xs-12">
                    <div class="services-item rounded">
                        <div class="icon">
                            <i class="lni-pencil-alt"></i>
                        </div>
                        <div class="services-content">
                            <h3 class="border-bottom mb-3">
                                <a href="#">Pengajuan Baru</a>
                            </h3>
                            <p>Klik pada tombol berikut untuk melakukan pengajuan layanan {{ $layanan->layanan }}</p>
                            <a href="{{ route('user.pengajuan.create', $layanan->url) }}" class="btn btn-common mt-3"><i
                                    class="lni-pencil-alt"></i> Buat Pengajuan Baru</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/mail.blade.php
<p>Hallo, saya {{ $data['name'] }}</p>
<p>Saya punya beberapa pertanyaan seperti {{ $data['message'] }}.</p>
<p>Akan sangat menghargai, jika Anda membalas pesan saya.</p>