routes/web.php
<?php

use App\Http\Controllers\PagesController;
use App\Http\Controllers\User\AccountController;
use App\Http\Controllers\User\ChatController;
use App\Http\Controllers\User\NotifikasiController;
use App\Http\Controllers\User\PengajuanController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PagesController::class, 'index'])->name('index');
Route::get('/layanan', [PagesController::class, 'showLayanan'])->name('layanan');
Route::get('/layanan/{url}', [PagesController::class, 'detailLayanan'])->name('layanan.detail');
Route::get('/tanya-jawab', [PagesController::class, 'showTanyaJawab'])->name('tanya-jawab');
Route::get('/kontak-kami', [PagesController::class, 'showKontakKami'])->name('kontak-kami');
Route::post('/send-message', [PagesController::class, 'sendMessage'])->name('send-message');

Route::group(['middleware' => 'auth', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
        Route::get('/', [PengajuanController::class, 'index'])->name('index');
        Route::get('/{url}/create', [PengajuanController::class, 'create'])->name('create');
        Route::post('/{url}/store', [PengajuanController::class, 'store'])->name('store');
        Route::get('/{no_pengajuan}/show', [PengajuanController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}/cancel', [PengajuanController::class, 'cancel'])->name('cancel');
        Route::get('/dokumen/{file}/download', [PengajuanController::class, 'downloadDokumen'])->name('download-dokumen');
    });
    Route::group(['prefix' => 'notifikasi', 'as' => 'notifikasi.'], function () {
        Route::get('/', [NotifikasiController::class, 'index'])->name('index');
        Route::get('/data', [NotifikasiController::class, 'data'])->name('data');
        Route::get('/count', [NotifikasiController::class, 'count'])->name('count');
        Route::get('/read/all', [NotifikasiController::class, 'readAll'])->name('read-all');
        Route::get('/{id}/read', [NotifikasiController::class, 'read'])->name('read');
    });
    Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
        Route::get('/', [AccountController::class, 'index'])->name('index');
        Route::post('/update', [AccountController::class, 'update'])->name('update');
        Route::get('/change-password', [AccountController::class, 'changePassword'])->name('change-password');
        Route::post('/update-password', [AccountController::class, 'updatePassword'])->name('update-password');
    });

    Route::group(['prefix' => 'chat', 'as' => 'chat.'], function () {
        Route::get('/{no_pengajuan}', [ChatController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}', [ChatController::class, 'send'])->name('send');
    });
});

Auth::routes();

app/Http/Controllers/User/ChatController.php
<?php

namespace App\Http\Controllers\User;

use App\Events\ChatWarga;
use App\Http\Controllers\Controller;
use App\Models\Pengajuan;
use App\Models\PengajuanChat;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ChatController extends Controller
{
    public function show($no_pengajuan)
    {
        $pengajuan = Pengajuan::where('no_pengajuan', $no_pengajuan)->with(['pengajuanChat'])->first();
        if (!$pengajuan) {
            return abort('404');
        }
        return view('chat.show', compact('pengajuan'));
    }

    public function send(Request $request, $no_pengajuan)
    {
        if ($request->ajax()) {
            $validator = Validator::make($request->all(), [
                'message' => 'required|string|max:255',
            ]);

            if ($validator->fails()) {
                return response()->json(['failed' => $validator->errors()->toArray()]);
            }

            PengajuanChat::where('no_pengajuan', $no_pengajuan)->where('to_warga', true)->update([
                'readed' => true,
            ]);

            $pengajuan_chat = PengajuanChat::create([
                'no_pengajuan' => $no_pengajuan,
                'body' => $request->message,
                'to_warga' => false,
                'to_user' => true,
                'readed' => false,
            ]);

            $data = [
                'no_pengajuan' => $pengajuan_chat->no_pengajuan,
                'profil' => $pengajuan_chat->pengajuan->warga->profil,
                'body' => $pengajuan_chat->body,
                'waktu' => date('h:i A', strtotime($pengajuan_chat->created_at)),
                'tanggal' => date('d M Y', strtotime($pengajuan_chat->created_at))
            ];

            event(new ChatWarga($data));

            return response()->json(['data' => $data]);
        }
    }
}

resources/views/chat/show.blade.php
@extends('layouts.app')

@section('title', 'Chat')

@push('my-css')
    <style>
        ::-webkit-scrollbar {
            width: 5px;
        }

        ::-webkit-scrollbar-track {
            width: 5px;
            background: #f5f5f5;
        }

        ::-webkit-scrollbar-thumb {
            width: 1em;
            background-color: #ddd;
            outline: 1px solid slategrey;
            border-radius: 1rem;
        }

        .text-small {
            font-size: 0.9rem;
        }

        .messages-box,
        .chat-box {
            height: 290px;
            overflow-y: scroll;
        }

        .rounded-lg {
            border-radius: 0.5rem;
        }

        input::placeholder {
            font-size: 0.9rem;
            color: #999;
        }

    </style>
@endpush

@section('content')
    <div class="page-header" style="background: url({{ asset('') }}assets/img/banner1.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="product-title">Chat</h2>
                        <ol class="breadcrumb">
                            <li><a href="{{ route('index') }}">Home /</a></li>
                            <li class="current">Chat</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="content" class="section-padding">
        <div class="container">
            <div class="row">
                @if (Session::has('success'))
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ Session::get('success') }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                @endif
                <div class="col-sm-12 col-md-4 col-lg-3 page-sidebar">
                    @include('layouts.aside')
                </div>
                <div class="col-sm-12 col-md-8 col-lg-9 no_pengajuan" data="{{ $pengajuan->no_pengajuan }}">
                    <div class="page-content">
                        <div class="inner-box">
                            <div class="dashboard-box">
                                <h2 class="dashbord-title">Chat Pengajuan {{ $pengajuan->layanan->layanan }}</h2>
                            </div>
                            <div class="dashboard-wrapper">
                                <div class="dashboard-wrapper">
                                    <div class="px-4 py-2 chat-box bg-white chat_message">
                                        @forelse ($pengajuan->pengajuanChat as $chat)
                                            @if ($chat->to_warga)
                                                <div class="media w-50 mb-3">
                                                    <img src="{{ asset('') }}favicon.png" alt="operator" width="50"
                                                        class="rounded-circle">
                                                    <div class="media-body ml-3">
                                                        <div class="bg-light rounded py-2 px-3 mb-1">
                                                            <p class="text-small mb-0 text-muted">
                                                                {{ $chat->body }}
                                                            </p>
                                                        </div>
                                                        <p class="small text-muted">
                                                            {{ date('h:i A', strtotime($chat->created_at)) }} |
                                                            {{ date('d M Y', strtotime($chat->created_at)) }}
                                                        </p>
                                                    </div>
                                                </div>
                                            @elseif ($chat->to_user)
                                                <div class="media w-50 ml-auto mb-3">
                                                    <div class="media-body">
                                                        <div class="bg-primary rounded py-2 px-3 mb-2">
                                                            <p class="text-small mb-0 text-white">{{ $chat->body }}</p>
                                                        </div>
                                                        <p class="small text-muted">
                                                            {{ date('h:i A', strtotime($chat->created_at)) }} |
                                                            {{ date('d M Y', strtotime($chat->created_at)) }}</p>
                                                    </div>
                                                </div>
                                            @endif
                                        @empty
                                            <div class="media w-50 mb-3 no_message">
                                                <img src="{{ asset('') }}favicon.png" alt="operator" width="50"
                                                    class="rounded-circle">
                                                <div class="media-body ml-3">
                                                    <div class="bg-light rounded py-2 px-3 mb-1">
                                                        <p class="text-small mb-0 text-muted">Hallo, ada yang bisa saya
                                                            bantu?
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        @endforelse
                                    </div>
                                    <form action="{{ route('user.chat.send', $pengajuan->no_pengajuan) }}"
                                        class="bg-light form_chat" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        <div class="input-group">
                                            <input type="text" placeholder="Type a message" aria-describedby="button-addon2"
                                                class="form-control rounded-0 border-0 py-3 bg-light" name="message"
                                                id="message">
                                            <div class="input-group-append">
                                                <button id="button-addon2" type="submit" class="btn btn-primary">
                                                    Kirim
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                    <small class="text-danger text_error" id="message_error"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('my-js')
    <script src="{{ asset('') }}scripts/chat/message.js"></script>
    <script src="{{ asset('') }}scripts/chat/send.js"></script>
@endpush