routes/web.php
<?php

use App\Http\Controllers\PagesController;
use App\Http\Controllers\User\AccountController;
use App\Http\Controllers\User\ChatController;
use App\Http\Controllers\User\NotifikasiController;
use App\Http\Controllers\User\PengajuanController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PagesController::class, 'index'])->name('index');
Route::get('/layanan', [PagesController::class, 'showLayanan'])->name('layanan');
Route::get('/layanan/{url}', [PagesController::class, 'detailLayanan'])->name('layanan.detail');
Route::get('/tanya-jawab', [PagesController::class, 'showTanyaJawab'])->name('tanya-jawab');
Route::get('/kontak-kami', [PagesController::class, 'showKontakKami'])->name('kontak-kami');
Route::post('/send-message', [PagesController::class, 'sendMessage'])->name('send-message');

Route::group(['middleware' => 'auth', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
        Route::get('/', [PengajuanController::class, 'index'])->name('index');
        Route::get('/{url}/create', [PengajuanController::class, 'create'])->name('create');
        Route::post('/{url}/store', [PengajuanController::class, 'store'])->name('store');
        Route::get('/{no_pengajuan}/show', [PengajuanController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}/cancel', [PengajuanController::class, 'cancel'])->name('cancel');
        Route::get('/dokumen/{file}/download', [PengajuanController::class, 'downloadDokumen'])->name('download-dokumen');
    });
    Route::group(['prefix' => 'notifikasi', 'as' => 'notifikasi.'], function () {
        Route::get('/', [NotifikasiController::class, 'index'])->name('index');
        Route::get('/data', [NotifikasiController::class, 'data'])->name('data');
        Route::get('/count', [NotifikasiController::class, 'count'])->name('count');
        Route::get('/read/all', [NotifikasiController::class, 'readAll'])->name('read-all');
        Route::get('/{id}/read', [NotifikasiController::class, 'read'])->name('read');
    });
    Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
        Route::get('/', [AccountController::class, 'index'])->name('index');
        Route::post('/update', [AccountController::class, 'update'])->name('update');
        Route::get('/change-password', [AccountController::class, 'changePassword'])->name('change-password');
        Route::post('/update-password', [AccountController::class, 'updatePassword'])->name('update-password');
    });

    Route::group(['prefix' => 'chat', 'as' => 'chat.'], function () {
        Route::get('/{no_pengajuan}', [ChatController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}', [ChatController::class, 'send'])->name('send');
    });
});

Auth::routes();

app/Models/Pengajuan.php
<?php

namespace App\Models;

use App\Models\MasterData\StatusPengajuan;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengajuan extends Model
{
    use HasFactory;

    protected $table = 'pengajuan';
    protected $primaryKey = 'no_pengajuan';
    public $incrementing = false;

    protected $guarded = [];

    public function data_pengajuan()
    {
        return $this->morphTo(__FUNCTION__, 'data_pengajuan_type', 'data_pengajuan_id');
    }

    public function warga()
    {
        return $this->belongsTo(User::class, 'id_warga', 'id');
    }

    public function layanan()
    {
        return $this->belongsTo(Layanan::class, 'id_layanan', 'id');
    }

    public function statusPengajuan()
    {
        return $this->belongsTo(StatusPengajuan::class, 'status', 'kode');
    }

    public function pengajuanUpload()
    {
        return $this->hasMany(PengajuanUpload::class, 'no_pengajuan', 'no_pengajuan');
    }

    public function pengajuanChat()
    {
        return $this->hasMany(PengajuanChat::class, 'no_pengajuan', 'no_pengajuan');
    }

    public function pengajuanRiwayat()
    {
        return $this->hasMany(PengajuanRiwayat::class, 'no_pengajuan', 'no_pengajuan');
    }
}

app/Http/Controllers/User/PengajuanController.php
<?php

namespace App\Http\Controllers\User;

use App\Events\SendNotification;
use App\Http\Controllers\Controller;
use App\Models\DataKelahiran;
use App\Models\DataLahirMati;
use App\Models\DataPembatalanPerkawinan;
use App\Models\DataPengajuan\KtpElektronikBaru;
use App\Models\DataPengajuan\KtpElektronikPerubahan;
use App\Models\DataPerkawinan;
use App\Models\Layanan;
use App\Models\LayananDokumen;
use App\Models\Notifikasi;
use App\Models\Pengajuan;
use App\Models\PengajuanRiwayat;
use App\Models\PengajuanUpload;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class PengajuanController extends Controller
{
    public function index()
    {
        return view('pengajuan.index');
    }

    public function create($url)
    {
        $layanan = Layanan::with(['layananDokumen', 'layananIsian', 'layananPersyaratan'])->where('url', $url)->first();
        if (!$layanan) {
            return abort('404');
        }
        return view('pengajuan.create', compact('layanan'));
    }

    public function store(Request $request, $url)
    {
        $layanan = Layanan::with(['layananDokumen', 'layananIsian', 'layananPersyaratan'])->where('url', $url)->first();
        if (!$layanan) {
            return abort('404');
        }

        // CEK JIKA SUDAH MENGAJUKAN
        $cek_sudah_mengajukan = Pengajuan::where('id_warga', auth()->id())->where('id_layanan', $layanan->id)->where('status', '!=', '3');
        if ($cek_sudah_mengajukan->count() > 0) {
            return redirect()->back()->with('failed', 'ANDA SUDAH MENGAJUKAN LAYANAN INI, HARAP CEK DAFTAR PENGAJUAN ANDA!');
        }

        // validasi berkas persyaratan
        if ($request->berkas) {
            foreach ($request->berkas as $index => $berkas) {
                if ($berkas['wajib'] == 1) {
                    $request->validate([
                        'berkas.' . $index . '.file' => 'required|mimes:jpeg,jpg,png,pdf|max:1200',
                    ]);
                } else {
                    $request->validate([
                        'berkas.' . $index . '.file' => 'nullable|mimes:jpeg,jpg,png,pdf|max:1200',
                    ]);
                }
            }
        }

        if ($layanan->id == 1) {
            $request->validate([
                'nama_lengkap' => 'required|string|max:255',
                'tempat_lahir' => 'required|string|max:255',
                'tgl_lahir' => ['required', 'date_format:Y-m-d'],
                'jenis_kelamin' => 'required|string|max:255',
                'nama_ibu' => 'required|string|max:255',
                'gol_darah' => 'required|string|max:255',
                'kewarganegaraan' => 'required|string|max:255',
                'alamat' => 'required|string|max:255',
                'rt' => 'required|string|max:5',
                'rw' => 'required|string|max:5',
                'kelurahan' => 'required|string|max:255',
                'kecamatan' => 'required|string|max:255',
                'kota' => 'required|string|max:255',
                'provinsi' => 'required|string|max:255',
                'kode_pos' => 'nullable|string|max:10',
                'terms' => 'required',
            ]);

            $data_pengajuan = KtpElektronikBaru::create([
                'nama_lengkap' => $request->nama_lengkap,
                'tempat_lahir' => $request->tempat_lahir,
                'tgl_lahir' => $request->tgl_lahir,
                'jenis_kelamin' => $request->jenis_kelamin,
                'nama_ibu' => $request->nama_ibu,
                'gol_darah' => $request->gol_darah,
                'kewarganegaraan' => $request->kewarganegaraan,
                'alamat' => $request->alamat,
                'rt' => $request->rt,
                'rw' => $request->rw,
                'kelurahan' => $request->kelurahan,
                'kecamatan' => $request->kecamatan,
                'kota' => $request->kota,
                'provinsi' => $request->provinsi,
                'kode_pos' => $request->kode_pos,
            ]);
        } elseif ($layanan->id == 2) {
            $request->validate([
                'nama_lengkap' => 'required|string|max:255',
                'nik' => 'required|numeric|digits:16,16',
                'alamat_rumah' => 'required|string|max:255',
                'pendidikan_terakhir_semula' => 'required|string|max:255',
                'pendidikan_terakhir_menjadi' => 'required|string|max:255',
                'pendidikan_terakhir_dasar_perubahan' => 'nullable|string|max:255',
                'pendidikan_terakhir_no' => 'nullable|string|max:255',
                'pendidikan_terakhir_tgl' => 'nullable|date_format:Y-m-d',
                'pekerjaan_semula' => 'required|string|max:255',
                'pekerjaan_menjadi' => 'required|string|max:255',
                'pekerjaan_dasar_perubahan' => 'nullable|string|max:255',
                'pekerjaan_no' => 'nullable|string|max:255',
                'pekerjaan_tgl' => 'nullable|date_format:Y-m-d',
                'agama_semula' => 'required|string|max:255',
                'agama_menjadi' => 'required|string|max:255',
                'agama_dasar_perubahan' => 'nullable|string|max:255',
                'agama_no' => 'nullable|string|max:255',
                'agama_tgl' => 'nullable|date_format:Y-m-d',
                'perubahan_lainnya_semula' => 'nullable|string|max:255',
                'perubahan_lainnya_menjadi' => 'nullable|string|max:255',
                'perubahan_lainnya_dasar_perubahan' => 'nullable|string|max:255',
                'perubahan_lainnya_no' => 'nullable|string|max:255',
                'perubahan_lainnya_tgl' => 'nullable|date_format:Y-m-d',
            ]);

            $data_pengajuan = KtpElektronikPerubahan::create([
                'nama_lengkap' => $request->nama_lengkap,
                'nik' => $request->nik,
                'alamat_rumah' => $request->alamat_rumah,
                'pendidikan_terakhir_semula' => $request->pendidikan_terakhir_semula,
                'pendidikan_terakhir_menjadi' => $request->pendidikan_terakhir_menjadi,
                'pendidikan_terakhir_dasar_perubahan' => $request->pendidikan_terakhir_dasar_perubahan,
                'pendidikan_terakhir_no' => $request->pendidikan_terakhir_no,
                'pendidikan_terakhir_tgl' => $request->pendidikan_terakhir_tgl,
                'pekerjaan_semula' => $request->pekerjaan_semula,
                'pekerjaan_menjadi' => $request->pekerjaan_menjadi,
                'pekerjaan_dasar_perubahan' => $request->pekerjaan_dasar_perubahan,
                'pekerjaan_no' => $request->pekerjaan_no,
                'pekerjaan_tgl' => $request->pekerjaan_tgl,
                'agama_semula' => $request->agama_semula,
                'agama_menjadi' => $request->agama_menjadi,
                'agama_dasar_perubahan' => $request->agama_dasar_perubahan,
                'agama_no' => $request->agama_no,
                'agama_tgl' => $request->agama_tgl,
                'perubahan_lainnya_semula' => $request->perubahan_lainnya_semula,
                'perubahan_lainnya_menjadi' => $request->perubahan_lainnya_menjadi,
                'perubahan_lainnya_dasar_perubahan' => $request->perubahan_lainnya_dasar_perubahan,
                'perubahan_lainnya_no' => $request->perubahan_lainnya_no,
                'perubahan_lainnya_tgl' => $request->perubahan_lainnya_tgl,
            ]);
        } elseif ($layanan->id == 3) {
            $request->validate([
                'nama_pelapor' => 'required|string|max:255',
                'nik' => 'required|numeric|digits:16,16',
                'nomor_kartu_keluarga' => 'required|string|max:255',
                'kewarganegaraan' => 'required|string|max:255',
                'nama_anak' => 'required|string|max:255',
                'jenis_kelamin_anak' => 'required|string|max:255',
                'tmpt_dilahirkan_anak' => 'required|string|max:255',
                'tmpt_kelahiran_anak' => 'required|string|max:255',
                'hari_lahir_anak' => 'required|string|max:255',
                'tgl_lahir_anak' => ['required', 'date_format:Y-m-d'],
                'waktu_lahir_anak' => 'required|date_format:H:i',
                'jenis_kelahiran_anak' => 'required|string|max:255',
                'kelahiran_ke_anak' => 'required|string|max:255',
                'penolong_kelahiran_anak' => 'required|string|max:255',
                'berat_bayi_anak' => 'required|string|max:255',
                'panjang_bayi_anak' => 'required|string|max:255',
                'nama_ayah' => 'required|string|max:255',
                'nik_ayah' => 'required|numeric|digits:16,16',
                'tempat_lahir_ayah' => 'required|string|max:255',
                'tgl_lahir_ayah' => ['required', 'date_format:Y-m-d'],
                'kewarganegaraan_ayah' => 'required|string|max:255',
                'nama_ibu' => 'required|string|max:255',
                'nik_ibu' => 'required|numeric|digits:16,16',
                'tempat_lahir_ibu' => 'required|string|max:255',
                'tgl_lahir_ibu' => ['required', 'date_format:Y-m-d'],
                'kewarganegaraan_ibu' => 'required|string|max:255',
                'nama_saksi_1' => 'required|string|max:255',
                'nik_saksi_1' => 'required|numeric|digits:16,16',
                'no_kk_saksi_1' => 'required|string|max:255',
                'kewarganegaraan_saksi_1' => 'required|string|max:255',
                'nama_saksi_2' => 'required|string|max:255',
                'nik_saksi_2' => 'required|numeric|digits:16,16',
                'no_kk_saksi_2' => 'required|string|max:255',
                'kewarganegaraan_saksi_2' => 'required|string|max:255',
            ]);

            $data_pengajuan = DataKelahiran::create([
                'nama_pelapor' => $request->nama_pelapor,
                'nik' => $request->nik,
                'nomor_kartu_keluarga' => $request->nomor_kartu_keluarga,

resources/views/pengajuan/index.blade.php
@extends('layouts.app')

@section('title', 'Pengajuan Saya')

@section('content')
    <div class="page-header" style="background: url({{ asset('') }}assets/img/banner1.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="product-title">Pengajuan Saya</h2>
                        <ol class="breadcrumb">
                            <li><a href="{{ route('index') }}">Home /</a></li>
                            <li class="current">Pengajuan Saya</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="content" class="section-padding">
        <div class="container">
            <div class="row">
                @if (Session::has('success'))
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ Session::get('success') }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                @endif
                <div class="col-sm-12 col-md-4 col-lg-3 page-sidebar">
                    @include('layouts.aside')
                </div>
                <div class="col-sm-12 col-md-8 col-lg-9">
                    <div class="page-content">
                        <div class="inner-box">
                            <div class="dashboard-box">
                                <h2 class="dashbord-title">Pengajuan Saya</h2>
                            </div>
                            <div class="dashboard-wrapper">
                                <nav class="nav-table">
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        @foreach (get_status_pengajuan() as $status_pengajuan)
                                            <li class="nav-item">
                                                <a class="nav-link {{ $status_pengajuan->kode == '1' ? 'active' : '' }}"
                                                    id="{{ $status_pengajuan->kode }}-tab" data-toggle="tab"
                                                    href="#{{ $status_pengajuan->kode }}" role="tab"
                                                    aria-controls="{{ $status_pengajuan->kode }}" aria-selected="true">
                                                    <span>
                                                        {{ strtoupper($status_pengajuan->nama) }}
                                                    </span>
                                                </a>
                                            </li>
                                        @endforeach
                                    </ul>
                                </nav>
                                <div class="tab-content" id="myTabContent">
                                    @foreach (get_status_pengajuan() as $status_pengajuan)
                                        <div class="tab-pane fade {{ $status_pengajuan->kode == '1' ? 'show active' : '' }}"
                                            id="{{ $status_pengajuan->kode }}" role="tabpanel"
                                            aria-labelledby="{{ $status_pengajuan->kode }}-tab">
                                            @if (get_pengajuan_saya($status_pengajuan->kode)->count() > 0)
                                                <table class="table table-responsive dashboardtable tablemyads">
                                                    <thead>
                                                        <tr style="width: 100%;">
                                                            <th class="align-middle">NO</th>
                                                            <th class="align-middle" style="width: 50%;">LAYANAN</th>
                                                            <th class="align-middle" style="width: 20%;">TANGGAL</th>
                                                            <th class="align-middle" style="width: 25%;">ACTION
                                                            </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (get_pengajuan_saya($status_pengajuan->kode) as $pengajuan)
                                                            <tr>
                                                                <td>{{ $loop->iteration }}</td>
                                                                <td>
                                                                    <h3>{{ $pengajuan->layanan->layanan }}</h3>
                                                                    @if (get_riwayat_pengajuan_terbaru($pengajuan->no_pengajuan))
                                                                        <span
                                                                            class="text-info">{{ get_riwayat_pengajuan_terbaru($pengajuan->no_pengajuan)->keterangan }}</span>
                                                                    @endif
                                                                </td>
                                                                <td>
                                                                    <span>
                                                                        {{ \Carbon\Carbon::parse($pengajuan->created_at)->isoFormat('D MMMM Y') }}
                                                                    </span>
                                                                </td>
                                                                <td>
                                                                    <div class="btns-actions">
                                                                        @if ($pengajuan->status !== '3')
                                                                            <a class="btn-action btn-view"
                                                                                href="{{ route('user.chat.show', $pengajuan->no_pengajuan) }}"
                                                                                title="Hubungi Operator">
                                                                                <i class="lni-bubble"></i>
                                                                            </a>
                                                                        @endif
                                                                        <a class="btn-action btn-edit"
                                                                            href="{{ route('user.pengajuan.show', $pengajuan->no_pengajuan) }}"
                                                                            title="Detail">
                                                                            <i class="lni-eye"></i>
                                                                        </a>
                                                                        @if ($pengajuan->status == '1')
                                                                            <a class="btn-action btn-delete btn_cancel"
                                                                                href="{{ route('user.pengajuan.cancel', $pengajuan->no_pengajuan) }}"
                                                                                title="Batalkan"
                                                                                id="{{ $pengajuan->no_pengajuan }}">
                                                                                <i class="lni-power-switch"></i>
                                                                            </a>
                                                                            <form
                                                                                action="{{ route('user.pengajuan.cancel', $pengajuan->no_pengajuan) }}"
                                                                                method="POST"
                                                                                id="form_{{ $pengajuan->no_pengajuan }}"
                                                                                class="d-none form_cancel">
                                                                                @csrf
                                                                            </form>
                                                                        @endif
                                                                    </div>
                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    </tbody>
                                                </table>
                                            @else
                                                <div class="p-5 text-center">
                                                    <img src="{{ asset('') }}assets/img/no-data.png"
                                                        class="img-fluid" alt="no-data">
                                                    <br>
                                                    <span>BELUM ADA PENGAJUAN</span>
                                                </div>
                                            @endif
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('my-js')
    <script>
        $(document).ready(function() {
            $(".btn_cancel").on("click", function(event) {
                event.preventDefault();
                Swal.fire({
                    title: 'Batalkan Pengajuan?',
                    text: "Anda akan membatalkan pengajuan ini!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya',
                    cancelButtonText: 'Tidak'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $('#form_' + $(this).attr('id')).submit();
                    }
                })
            });
        });
    </script>
@endpush