routes/web.php
<?php

use App\Http\Controllers\PagesController;
use App\Http\Controllers\User\AccountController;
use App\Http\Controllers\User\ChatController;
use App\Http\Controllers\User\NotifikasiController;
use App\Http\Controllers\User\PengajuanController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PagesController::class, 'index'])->name('index');
Route::get('/layanan', [PagesController::class, 'showLayanan'])->name('layanan');
Route::get('/layanan/{url}', [PagesController::class, 'detailLayanan'])->name('layanan.detail');
Route::get('/tanya-jawab', [PagesController::class, 'showTanyaJawab'])->name('tanya-jawab');
Route::get('/kontak-kami', [PagesController::class, 'showKontakKami'])->name('kontak-kami');
Route::post('/send-message', [PagesController::class, 'sendMessage'])->name('send-message');

Route::group(['middleware' => 'auth', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
        Route::get('/', [PengajuanController::class, 'index'])->name('index');
        Route::get('/{url}/create', [PengajuanController::class, 'create'])->name('create');
        Route::post('/{url}/store', [PengajuanController::class, 'store'])->name('store');
        Route::get('/{no_pengajuan}/show', [PengajuanController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}/cancel', [PengajuanController::class, 'cancel'])->name('cancel');
        Route::get('/dokumen/{file}/download', [PengajuanController::class, 'downloadDokumen'])->name('download-dokumen');
    });
    Route::group(['prefix' => 'notifikasi', 'as' => 'notifikasi.'], function () {
        Route::get('/', [NotifikasiController::class, 'index'])->name('index');
        Route::get('/data', [NotifikasiController::class, 'data'])->name('data');
        Route::get('/count', [NotifikasiController::class, 'count'])->name('count');
        Route::get('/read/all', [NotifikasiController::class, 'readAll'])->name('read-all');
        Route::get('/{id}/read', [NotifikasiController::class, 'read'])->name('read');
    });
    Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
        Route::get('/', [AccountController::class, 'index'])->name('index');
        Route::post('/update', [AccountController::class, 'update'])->name('update');
        Route::get('/change-password', [AccountController::class, 'changePassword'])->name('change-password');
        Route::post('/update-password', [AccountController::class, 'updatePassword'])->name('update-password');
    });

    Route::group(['prefix' => 'chat', 'as' => 'chat.'], function () {
        Route::get('/{no_pengajuan}', [ChatController::class, 'show'])->name('show');
        Route::post('/{no_pengajuan}', [ChatController::class, 'send'])->name('send');
    });
});

Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @hasSection('title')
        <title>@yield('title')&nbsp;-&nbsp;{{ config('app.name') }}</title>
    @else
        <title>{{ config('app.name') }}</title>
    @endif
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('') }}favicon.png">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/fonts/line-icons.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/css/slicknav.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/css/animate.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/css/main.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/css/responsive.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('') }}assets/vendors/sweetalert/sweetalert2.css">
    @stack('my-css')
</head>

<body>
    @include('layouts.app.header')

    @yield('content')

    @include('layouts.app.footer')

    <a href="#" class="back-to-top">
        <i class="lni-chevron-up"></i>
    </a>

    <div id="preloader">
        <div class="loader" id="loader-1"></div>
    </div>

    <script src="{{ asset('') }}assets/js/jquery-min.js"></script>
    <script src="{{ asset('') }}assets/js/popper.min.js"></script>
    <script src="{{ asset('') }}assets/js/bootstrap.min.js"></script>
    <script src="{{ asset('') }}assets/js/jquery.counterup.min.js"></script>
    <script src="{{ asset('') }}assets/js/waypoints.min.js"></script>
    <script src="{{ asset('') }}assets/js/wow.js"></script>
    <script src="{{ asset('') }}assets/js/owl.carousel.min.js"></script>
    <script src="{{ asset('') }}assets/js/jquery.slicknav.js"></script>
    <script src="{{ asset('') }}assets/js/main.js"></script>
    <script src="{{ asset('') }}assets/js/form-validator.min.js"></script>
    <script src="{{ asset('') }}assets/js/contact-form-script.min.js"></script>
    <script src="{{ asset('') }}assets/js/summernote.js"></script>
    <script src="{{ asset('') }}assets/vendors/sweetalert/sweetalert2.js"></script>
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    @auth
        <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
        <script src="{{ asset('') }}scripts/pusher.js"></script>
        <script src="{{ asset('') }}scripts/notifikasi/count.js"></script>
    @endauth

    @stack('my-js')
</body>

</html>

resources/views/layouts/aside.blade.php
<aside>
    <div class="sidebar-box">
        <div class="user">
            <figure>
                <img src="{{ asset('') }}profil-user/{{ auth()->user()->profil }}" alt="" class="w-50">
            </figure>
            <div class="usercontent">
                <h3>{{ auth()->user()->nama_lengkap }}</h3>
                <h4>{{ auth()->user()->email }}</h4>
            </div>
        </div>
        <nav class="navdashboard">
            <ul>
                <li>
                    <a class="{{ Request::is('user/pengajuan') || Request::is('user/pengajuan/*') ? 'active' : '' }}"
                        href="{{ route('user.pengajuan.index') }}">
                        <i class="lni-files"></i>
                        <span>Pengajuan Saya</span>
                    </a>
                </li>
                <li>
                    <a class="{{ Request::is('user/notifikasi') || Request::is('user/notifikasi/*') ? 'active' : '' }}"
                        href="{{ route('user.notifikasi.index') }}">
                        <i class="lni-alarm"></i>
                        <span>
                            Notifikasi
                            &nbsp;
                            <sup class="count_notifikasi justify-content-end"></sup>
                        </span>
                    </a>
                </li>
                <li>
                    <a class="{{ Request::is('user/account') ? 'active' : '' }}"
                        href="{{ route('user.account.index') }}">
                        <i class="lni-user"></i>
                        <span>Akun Saya</span>
                    </a>
                </li>
                <li>
                    <a class="{{ Request::is('user/account/change-password') ? 'active' : '' }}"
                        href="{{ route('user.account.change-password') }}">
                        <i class="lni-cog"></i>
                        <span>Ubah Password</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();document.getElementById('form-logout').submit();">
                        <i class="lni-enter"></i>
                        <span>Logout</span>
                    </a>
                    <form id="form-logout" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </li>
            </ul>
        </nav>
    </div>
</aside>